FnxFinanceiroBundle:
    resource: "@FnxFinanceiroBundle/Controller/"
    type:     annotation
    prefix:   /

FnxAdminBundle:
    resource: "@FnxAdminBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

FnxPedidoBundle:
    resource: "@FnxPedidoBundle/Controller/"
    type:      annotation
    prefix:   "adm/"
