security:
    encoders:
        Fnx\AdminBundle\Entity\Usuario:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    
    providers:
        entity_user:
            entity: { class: FnxAdminBundle:Usuario, property: username }

    firewalls:
            
        login_user:
            pattern:  ^/user/login$
            security: false
            anonymous: true
            
        login_admin:
            pattern:  ^/adm/login$
            security: false
            anonymous: true
            
       
        admin_secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                check_path: /adm/login_check
                login_path: /adm/login
                default_target_path: /
            logout:
                path: /adm/logout
                target: /
            remember_me:
                key:      "%secret%"
                lifetime: 86400
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
       
#        user_secured_area:
#            pattern: ^/
#            anonymous: true
#            form_login:
#                check_path: /user/login_check
#                login_path: /user/login
#            logout:
#                path: /user/logout
#                target: /
#  
  
    access_control:
        - { path: /adm/change-password, roles: [ROLE_ADMIN,ROLE_FUNCIONARIO] }
        - { path: /adm/funcionario/show/, role: [ROLE_ADMIN,ROLE_FUNCIONARIO]}
        - { path: ^/admin, roles: [ROLE_ADMIN,ROLE_FUNCIONARIO]}
        - { path: ^/adm/, role: ROLE_ADMIN}
        - { path: ^/financeiro, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /adm/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user/login/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        

    acl:
        connection: default