<?php

namespace Fnx\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtividadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtividadeRepository extends EntityRepository
{
    
    public function loadLocal(){
        return $this->getEntityManager()
                    ->createQuery("SELECT l,a,c FROM FnxAdminBundle:Local l
                                   JOIN l.atividade a
                                   JOIN l.cidade c
                                   WHERE a.arquivado = :false")
                                   ->setParameters(array("false" => false))
                                   ->getResult();
    }
}