<?php

namespace Fnx\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AtividadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtividadeRepository extends EntityRepository
{
    public function loadLocal(){
        return $this->getEntityManager()
                    ->createQuery("SELECT l,a,c FROM FnxAdminBundle:Local l
                                   JOIN l.atividade a
                                   JOIN l.cidade c
                                   WHERE a.arquivado = :false")
                                   ->setParameters(array("false" => false))
                                   ->getResult();
    }
    
    public function loadAtividade(){
        return $this->getEntityManager()
                    ->createQuery("SELECT a,c,cl,s FROM FnxAdminBundle:Atividade a
                                   JOIN a.contrato c
                                   JOIN c.cliente cl
                                   JOIN a.servico s
                                   WHERE a.arquivado = :false
                                   AND a.dtInicio <> ''
                                   AND a.dtFim <> ''")
                                   ->setParameters(array("false" => false))
                                   ->getResult();
    }
    
    public function getByAgenda($data){
            
            
            $inicio = new \DateTime($data." 00:00:00");
            $fim = new \DateTime($data." 23:59:00");
            
            return $this->createQueryBuilder('a')
                ->select('a', 'cli', 'c', 's')
                ->join('a.contrato', 'c')
                ->join('c.cliente', 'cli')
                ->join('a.servico', 's')
                ->andWhere("a.arquivado = :false")
                ->andwhere("a.dtInicio <= :inicio")
                ->andWhere("a.dtFim >= :fim")
                ->setParameters(array("false" => false,
                                            "inicio" => $inicio,
                                            "fim" => $fim))
                ->getQuery()
                ->getResult();
                
    }
}