<?php

namespace Fnx\PedidoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends EntityRepository
{
        public function loadPedido($status) {

            $qb = $this->createQueryBuilder('p')
                ->select('p', 'c')
                ->join('p.cliente', 'c');

            if ($status != "t"){
                $qb->Where("p.status = :param")
                ->setParameters(array("param" => $status));
            }

            return $qb->getQuery()->getResult();
        }
}